# SAM FILE
AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: >
  lambda local demo

Resources:
  LambdaDemoFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/ # format is projectPath/
      Handler: lambda.lambdaHandler # format is filename.functionName
      Runtime: nodejs18.x

  ApiGatewayFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: apigateway/ # format is projectPath/
      Handler: apigateway.lambdaHandler # format is filename.functionName
      Runtime: nodejs18.x
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: 